### ISSUE TITLE
Question about multiple ObjectClasses

### ISSUE THREAD

**Issue by ThomasTosik** [wedoit-io/LDAP-Library#12]
Hi!

Neat little library you have there! Is it it possible to work with more than one ObjectClass? E.g. create a user as a "person" and a "posixAccount".

Regards

**Comment by benkio** [comment]
Hi,
Unfortunately we, as a company, didn't require this feature yet, so the library doesn't manage multiple ObjectClasses and right now this isn't planned. Anyway you can always fork from this and add the feature or make a pull request, if would be awesome. I don't know if there's a workaround for your needs with the current API. 
In conclusion i marked this issue as wontfix and i will keep this open, so all will be tracked.
Thanks for your question and sorry if i cannot be more helpfull.
Regards
